config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence:true
  validates :content, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.paginate(page: params[:page]).reverse_order
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(task_params)
    if @task.save
    redirect_to tasks_path
    else
      render new_task_path
    end
  end
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
  
  private 
    def task_params
      params.require(:task).permit(:title, :content)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@task.errors.count, "error") %>.
    </div>
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>内容編集</h1>
<div class="sbody">
<%= form_for(@task) do |f| %>
  <div><%= f.label :title%></div>
  <div><%= f.text_field :title %></div>
  <div><%= f.label :content %></div>
  <div><%= f.text_area :content, size:"50x10" %></div>
  <div><%= f.submit %></div>
<% end %>
<div><%= link_to '戻る', tasks_path, {class:"btn btn--blue btn--radius"}%></div>
</div>

app/views/tasks/index.html.erb
<h1>一言掲示板</h1>
  <div class="sbody">
    
    <div class="addbtn"><%= link_to '追加', new_task_path, {class:"btn btn--blue btn--radius"} %></div>
    <div>
    <%= will_paginate %>
    </div>
    <% @tasks.each do |task| %>
    <div class="adata">
      <div><h4><%= task.title %></h4></div>
      <div>
        <%= simple_format(task.content, class: "text") %>
        <%= task.created_at.in_time_zone('Tokyo') %>
      </div>
      <div>
        <%= link_to '編集', edit_task_path(task),{class:"btn btn--blue btn--radius"} %>
        <%= link_to '削除', task_path(task), {method: :delete,class:"btn btn--blue btn--radius"} %>
      </div>
    </div>
    <% end %>
    <div>
    <%= will_paginate %>
    </div>
</div>

app/views/tasks/new.html.erb
<h1>新規作成</h1>
<%= render 'shared/error_messages' %>
<div class="sbody">
<%= form_for(@task) do |f| %>
  <div><%= f.label :title %></div>
  <div><%= f.text_field :title, class:'form-control' %></div>
  <div><%= f.label :content %></div>
  <div><%= f.text_area :content, size:"50x10", class:'form-control'%></div>
  <div><%= f.submit "Post!", class:"btn btn--blue btn--radius" %></div>
<% end %>
<div><%= link_to '戻る', tasks_path ,{class:"btn btn--blue btn--radius"}%></div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>